version: '3'

tasks:
  lint:
    cmds:
      - poetry run ruff format --check
      - poetry run ruff check
  typecheck:
    cmds:
      - poetry run mypy .
  format:
    cmds:
      - poetry run ruff format
  run:
    cmds:
      - poetry run python3 main.py -c config.yaml

